### ISSUE TITLE
Release: Refresh browser raise 404 not found

### ISSUE THREAD

**Issue by BertrandRenault** [pixano/pixano#158]
## Bug description

With the release version only, everywhere except the starting page, when you refresh the browser (F5 key), you got a 404 not found

## Steps to reproduce

(better in a dedicated conda env)

1. pip install pixano==0.5.0b4
2. pixano my_dataset_library/
3. go to given url, select a dataset (or any page except the main page)
4. refresh

## Expected behavior

Not 404 !

## Additional context

tested with pixano==0.5.0b4

**Comment by BertrandRenault** [comment]
not sure of scope, but I suppose it is linked to svelte-kit routes

**Comment by timothee-LJN** [comment]
Not sure about the scope too, my first guess would be that it's about whitelisting url in the backend framework.
any idea @cpvannier ?

**Comment by cpvannier** [comment]
Looks like a conflict where the frontend routes are misinterpreted as API endpoints indeed.

It doesn't look like whitelisting is an option, especially since we don't have a static list of existing routes but generated routes based on the dataset and the item names.

From what I can find online it seems the solution would be to run the API endpoints and the frontend routes on two separate URLs to prevent conflicts, but I'm not sure how this would be done here.

**Comment by cpvannier** [comment]
> From what I can find online it seems the solution would be to run the API endpoints and the frontend routes on two separate URLs to prevent conflicts

This is actually the reason why reloading works with the local app. API endpoints are on `http://127.0.0.1:8000` while frontend routes are on `http://localhost:5173/`.

So the question is how can we replicate that setup in the deployed app. I wonder if it is possible with the SvelteKit static-adapter that we are currently using.
