### ISSUE TITLE
Crashes when buffering too many frames

### ISSUE THREAD

**Issue by cpvannier** [pixano/pixano#366]
## Bug description

> add a frame buffer for faster play (@BertrandRenault, #358)
> con: all calls to API for views at the start, all frames are loaded even if we just want a quick view on the item.

This is a bit of a problem actually. I am currently testing Pixano for multi-view video datasets, and the v0.6.0b5 works fine, but when running on the main branch with this commit, the tab often ends up crashing because it tries to load too many frames at once.

## Steps to reproduce

Opening a dataset item with long videos (e.g. 10 minutes or more) and/or multiple views (e.g. 5 cameras or more)

## Expected behavior

The buffer is a great idea, the stutter when playing in v0.6.0b5 is fixed in this commit (when it doesn't crash), but ideally it should only load the next few seconds, not the whole video.

Also, the buffer should load frame by frame, not view by view: here, it will load the whole 10 minutes for camera 1, then the whole 10 minutes for camera 2, etc. So when playing, camera 6 will not be displayed at all until all the other cameras have fully loaded.

## Additional context

_Originally posted by @cpvannier in https://github.com/pixano/pixano/issues/358#issuecomment-2500897742_

**Comment by juliendenize** [comment]
Yeah we should have a proper buffer that fetches content for the next seconds as some well known video stream platform (YT for example).

I believe that this buffer should be handled by the app and not the backend so that we keep things completly stateless (at least for now). We don't need to have all the frames during reading and we can free memory. The main difference with stream apps is that we need to have previous and after frames because the user will probably want to go before and ahead (more ahead than before I would assume).

@cpvannier could you specify what kind of buffer you'd like in your use case ?

**Comment by cpvannier** [comment]
> I believe that this buffer should be handled by the app and not the backend so that we keep things completly stateless (at least for now).

Yes the buffer added in #358 does not change the backend, and I think it should stay that way.

> could you specify what kind of buffer you'd like in your use case ?

When discussing with Bertrand, he mentioned using a circular buffer, i.e. a fixed-length buffer that keeps a few seconds before and after the current point loaded at all times, and discards the rest. If this can be implemented I think it would be a good solution.

**Comment by BertrandRenault** [comment]
I'm doing it actually (front side), it seems to work, execpt from some details I need to adress before submitting PR

**Comment by juliendenize** [comment]
The thing is, we should define what is the fixed-length. Because having a few seconds for 300fps video or 24 is not the same. The buffer should probably be of a fixed-size in terms of RAM storage and it should be multiview. This way, we handle the case where we have higher or lower framerates but also handle the multiview setting. The more views you have the less cache per view you can handle.

However it supposes we know the size of an image before downloading it to know if we need to free space or not. We do not store this metadata when we create the image in the database (maybe we should ?) so maybe we should have a route that get stats on media.
- so one route for getting media info
- one route for getting media (currently we mount the paths but I do not believe we should do it this way)
