### ISSUE TITLE
Error when using COCOImporter with multiple splits.

### ISSUE THREAD

**Issue by adbcode** [pixano/pixano#50]
I am using a COCO format dataset, created using supervision library:

![image](https://github.com/pixano/pixano/assets/9251629/0e33d315-27e0-48c1-9170-cfe33b6fe579)

When passing the splits as follows, the library does not behave as expected: `splits = ["test", "train", "valid"]`.

We notice the following issues in the explorer page:
- The id values for all images are set to 0: 
![image](https://github.com/pixano/pixano/assets/9251629/aec85834-b4be-440a-878d-f4139ffae749)
- The preview shows one image, but the one shown in full view is different.
- The mask data is used from the thumbnail mentioned above and not the displayed image.
- The splits shown in overview page does not correspond to the image shown in full view.

We have validated the images in another tool and noticed no such behaviour, and we get expected results when only using one split at a time.

Kindly investigate any potential issues with loading multiple splits, perhaps with how the id values are handled.

**Comment by cpvannier** [comment]
I tried importing a COCO dataset with 3 splits, and I can't seem to reproduce the issue.

Maybe you can try importing your dataset with the beta version that we just released (`python -m pip install==0.5.0b1`) to check if this was fixed by some of the changes we made in this release.

And if the issue still happens with that version, then there might be something unexpected in your JSON files that breaks the importer and that we have not yet encountered with our files. In that case, it would be a huge help if you could send us the files so we can try reproducing the issue.
